//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autopart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autopart()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int IdAutopart { get; set; }
        public string Title { get; set; }
        public int Qty { get; set; }
        public decimal Cost { get; set; }
        public int IdFirm { get; set; }

        //public string INFO { get => $"{Title} , {IdFirm.} , {}" }
    
        public virtual Firm Firm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}
